service: API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  iam:
      role:
          statements:
            - Effect: Allow
              Action: 
                - dynamodb: PutItem
                - dynamodb: UpdateItem
                - dynamodb: GetItem
                - dynamodb: scan

          Resource:
              - arn:aws:dynamodb:us-east-1:872231287375:table/ItemTable

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/handler.insertItem
    events:
      - httpApi:
          path: /item
          method: post  
  fetchItems:
    handler: src/handler.fetchItems
    events:
      - httpApi:
          path: /items
          method: get     
  fetchItem:
    handler: src/handler.fetchItem
    events:
      - httpApi:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/handler.updateItem
    events:
      - httpApi:
          path: /items/{id}
          method: put

resources:
  Resources:                                                                                                           
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH